"""refactor_replace_content_with_s3_path

Revision ID: efc0ab7c4c7e
Revises: 8652295713a2
Create Date: 2026-03-23 09:39:21.714270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc0ab7c4c7e'
down_revision: Union[str, Sequence[str], None] = '8652295713a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_files', sa.Column('s3_object_name', sa.String(), nullable=False))
    op.drop_column('extracted_files', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_files', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('extracted_files', 's3_object_name')
    # ### end Alembic commands ###
